version: "3"
services:
  frontend:
    build: 
      context: ./
      dockerfile: ./infra/frontend/Dockerfile
    tty: true
    volumes:
      - ./app/:/app
      - node_modules:/app/node_modules
    ports:
      - "${FRONT_PORT:-52373}:52373"
volumes:
  node_modules:
    driver: local